name: Manual Events
on: 
  workflow_dispatch:
    inputs:
      param1:
        description: 'Pram1 description'
        required: true
        default: 'Hello World'
jobs:
  run-manual-tasks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Run Manual Task
      run: |
        echo "Running manual tak with param1: ${{ github.event.inputs.param1 }}"
