name: Matrix Example

on:
  push:
    branches:
      - main

jobs:
  example_matrix:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Display matrix values
        run: |
          echo "Running on OS: ${{ matrix.os }}"
          echo "Using version: ${{ matrix.version }}"
